# Generated by Django 2.0.2 on 2018-04-27 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_excel', '0002_ipc_classification_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=200)),
                ('title', models.TextField()),
                ('patent', models.CharField(max_length=50)),
                ('classification', models.CharField(max_length=50)),
                ('inventor', models.CharField(max_length=50)),
                ('year_week', models.CharField(max_length=50)),
            ],
        ),
    ]
