# Generated by Django 2.0.2 on 2018-04-27 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_excel', '0007_auto_20180427_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventions',
            name='inventor',
            field=models.TextField(),
        ),
    ]
