# Generated by Django 2.0.2 on 2018-05-03 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_excel', '0010_excel_files'),
    ]

    operations = [
        migrations.CreateModel(
            name='Excel_Files1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('title', models.TextField()),
                ('filename', models.CharField(max_length=50)),
                ('year_week', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Excel_Files',
        ),
    ]
