# Generated by Django 2.0.2 on 2018-05-03 19:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('p_excel', '0011_auto_20180503_1432'),
    ]

    operations = [
        migrations.CreateModel(
            name='Excel_Files',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('title', models.TextField()),
                ('filename', models.CharField(max_length=50)),
                ('year_week', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Inventions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('link', models.URLField()),
                ('title', models.TextField()),
                ('untype', models.CharField(max_length=50)),
                ('patent', models.CharField(max_length=50)),
                ('classification', models.CharField(max_length=50)),
                ('inventor', models.TextField()),
                ('year_week', models.CharField(max_length=50)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='IPC_Codes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('title', models.TextField()),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.DeleteModel(
            name='Excel_Files1',
        ),
        migrations.DeleteModel(
            name='Inventions1',
        ),
        migrations.DeleteModel(
            name='IPC_Classification',
        ),
    ]
